### ISSUE TITLE
Comments are not displaying on posts with disabled comments

### ISSUE THREAD

**Issue by ghost** [Hyprtxt/bootstrapfour#2]
There is a post that originally had comments enabled and people posted on it.  

Later, comments are disabled, and no one is able to post new comments but the old published comments should still be shown - currently they are not.

PS: thank you - awesome theme!  Finally someone made a useable clean theme that's readable!

**Comment by digitaldesigndj** [comment]
PR's appreciated, I will check this out when I get some time.
