### ISSUE TITLE
Bootstrap tooltips require Tether

### ISSUE THREAD

**Issue by NoralK** [Hyprtxt/bootstrapfour#5]
I'm getting this JavaScript error:

```
SCRIPT5022: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)
File: bootstrap.js, Line: 2772, Column: 5
```

Any thoughts how to solve?
Noral

**Comment by digitaldesigndj** [comment]
You need tether: https://github.com/twbs/bootstrap/issues/17273

This one:
https://github.com/twbs/bootstrap/blob/v4-dev/docs/assets/js/vendor/tether.min.js#L1

And I need to update this to a newer bootstrap with newer issues! I did run into this myself... Thanks for the report!

**Comment by digitaldesigndj** [comment]
Tether is an additional dependency that hops up when you start using more of the JavaScript features of Bootstrap.
